os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: USK66fG+KQwqu3wBXo5GFO5rpgzKtC9B2gU7IO3bKmy0ulBWia1n/Fzq9tJUXDzhZxs4oNrhx5Vu042jSx8NQTzgH9wcKufCN7uRCkNXfwQ4OXfdvcw0nfYe15OR6LDKGcDCLC85NwSJr7xoTj8Xr7wGCxknl0Beljqm5cgbb/9vHv6t4yVObscmi87HZCZ7i6u52VWRkxXN6DmwNKjQB2SXSwPq4mLSUmfWRNUr6dSHyCMliOsHmzVQQHn3wHP+e3CGBUK80qBJ/xweGHYqYIVbLNBPak+RuGWTe4SzkRG5eCg64K8QyYiaJ1IzdBmjxt6lIARkPRP4gqLDrHYlVYesK8tQCmNNQDWN+pXUMzlHmWcBW8VxIOf6rUEHQKyF+HA8/fcQp8+zqo6c/n+h/IV7iy9MpZyG6feg2JpSU/NDyjgw933ZiYG9ETNW+zaW4rpV7nvI3NRFmwM4ecmdwzrDGqg4DNzmt/HW3keH6HEhyv3u8NhmmaMUqoT1Mo6BWHlA2Z4m47E33bQPqhGN6HCT5rwXCe+CaJYdvOqpLZNriDVyO1IAOU3Dfm0nsX24mtu97+mewczuZAq3nf03+PCaiKknP5cRw6LE+A4PFSQSZAyAQYNxJYa/GN+83Tm2zxtlgGgHCWpfSW1xrnGBhGp6PMOPt8JgAKNGeLNBBOw=
