os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: ipn2tkPU389JqOjUQm5KjLQdSNyqaA7cwAUIdzAlsQBGHggWwOjmPBGgInBUG8aQA1VZH8VgCI8Eyb/HxuZLcp9OJ89HfsSJRxFiUIxQ/DYOyTLwp2B793Rf7G1Vt1OrrVK9JTdljccqETn6gE4961WAmjJ0H+1UTbCUnCWRNpxmvdbmc6Uo+XNYoX+uLNjvupsucpXiFAO2gbLZeLCP1FQJTJOIFIfPoJq+gGhdn2/s5AjXWWCkOlZldXnfsdBysdJXbwNGDlQxqIYwkh3s84xHpAgUnkxs0NK9G1wPvdXRDKoqGb0O64Rg4Q5sybYoHzKJnFYDe3sOAfEHIDXf26K3eEbKo7kwXVj8Wi/KQDmNCjabeimXkSjq1tS76tely+pZEa9TZEhweXf7dKMOYH1oOT3ZBfb8NvcgU7Go88inTA4rt2Pvc+2His3gVK9ckdY880yV2H2cP1cjfWjMHS9Ep0qiACkzlVGozvmYlRjZAIS41/bW5iAS0/OwBkJ9Uol4wKXL+uTTIdcpPm+5JCgr2DYs6w+MA4n8jtBT7J+6m2ts6y5Zh8fAqUJbCsKhrn14ymb5Zf4qBy5rOBhXhVzEEdW/bB7zuL5PDyzURL/wLIGrQfYRJo7pC5Est/cULxVB7Z/Wt42qA93F2jpGzrXuxAJRw+6FoHAXg+6AUK8=
